# Generated by Django 4.1.5 on 2023-03-23 14:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField(default='', help_text='uid')),
                ('register', models.TextField(blank=True, default='21:57:45, 23.03.2023', help_text='Дата и время регистрации')),
                ('last_peer_id', models.TextField(default=0, help_text='ID диалога, из которого пришло последнее сообщение')),
                ('wrote_personal', models.BooleanField(default=False, help_text='Писал(-а) ли в личные сообщение?')),
                ('messages_count', models.BigIntegerField(default=0, help_text='Количество сообщений')),
                ('online_time', models.DateTimeField(default=datetime.datetime.now, help_text='Время онлайна')),
                ('nickname', models.TextField(blank=True, default='', help_text='Никнейм', null=True)),
                ('admin', models.BooleanField(default=False, help_text='Администратор')),
                ('ban', models.BooleanField(default=False, help_text='Бан')),
            ],
        ),
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField(blank=True, default='', help_text='ID беседы', null=True)),
                ('title', models.TextField(default='', help_text='название беседы')),
                ('activation', models.BooleanField(default=False, help_text='Активация')),
                ('malling', models.BooleanField(default=True, help_text='Рассылка')),
                ('prize', models.BooleanField(default=False, help_text='Получение приза')),
                ('keyboard', models.BooleanField(default=False)),
                ('games', models.BooleanField(default=True, help_text='Игры')),
                ('rules', models.TextField(blank=True, default='', help_text='Правила', null=True)),
                ('greeting', models.TextField(blank=True, default='', help_text='Приветствие', null=True)),
                ('messages', models.BigIntegerField(default=0, help_text='сообщения беседы')),
                ('type', models.BooleanField(default=False, help_text='админ беседа')),
            ],
            options={
                'verbose_name': 'Беседы',
                'verbose_name_plural': 'Беседы',
                'ordering': ('id', 'uid', 'activation', 'malling', 'prize', 'keyboard', 'games', 'rules', 'greeting', 'messages', 'type'),
            },
        ),
        migrations.CreateModel(
            name='WordFilters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(blank=True, default='', help_text='Слово', null=True)),
                ('chat', models.ForeignKey(blank=True, help_text='Беседа', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_WordFilters', to='app.chats')),
            ],
            options={
                'verbose_name': 'Фильтр слов (Беседы)',
                'verbose_name_plural': 'Фильтр слов (Беседы)',
                'ordering': ('id', 'word', 'chat'),
            },
        ),
        migrations.CreateModel(
            name='ChatsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_moder', models.BooleanField(default=False, help_text='Модератор')),
                ('is_admin', models.BooleanField(default=False, help_text='Админстратор')),
                ('is_owner', models.BooleanField(default=False, help_text='Основатель')),
                ('mention', models.BooleanField(default=True, help_text='Упоминание')),
                ('ban_time', models.DateTimeField(default=datetime.datetime.now, help_text='Время бана')),
                ('mute_time', models.DateTimeField(default=datetime.datetime.now, help_text='Время мута')),
                ('warns', models.IntegerField(default=0, help_text='Кол-во варнов')),
                ('chat', models.ForeignKey(blank=True, help_text='Беседа', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_ChatsUser', to='app.chats')),
                ('user', models.ForeignKey(blank=True, help_text='Пользователь', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_ChatsUser', to='app.account')),
            ],
            options={
                'verbose_name': 'Беседа (Пользователи)',
                'verbose_name_plural': 'Беседа (Пользователи)',
                'ordering': ('id', 'chat', 'user', 'is_moder', 'is_admin', 'is_owner', 'mention', 'ban_time', 'mute_time', 'warns'),
            },
        ),
    ]
